const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),start=document.querySelector('#startScreen'),startButton=document.querySelector('#startButton'),banner=document.querySelector('#roundBanner');
const W=canvas.width,H=canvas.height,floor=560,keys={};let running=false,last=0,sound=true,round=1,playerWins=0,enemyWins=0,screenShake=0,particles=[];
const audio=window.AudioContext?new AudioContext():null;
function beep(f,t=.06,type='square',v=.03){if(!sound||!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.value=v;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+t);o.stop(audio.currentTime+t)}
function make(x,color,name,flip){return{x,y:floor,vx:0,vy:0,color,name,flip,hp:100,maxHp:100,energy:0,attack:0,cool:0,flash:0,hit:false,defeated:false,attackType:'quick',combo:0,comboTimer:0,block:0,dodge:0,chain:0}}
let player,enemy;function reset(fresh=true){player=make(270,'#df3f43','SHADOW',false);enemy=make(900,'#7e9fb0','RONIN',true);enemy.maxHp=108+(round-1)*10;enemy.hp=enemy.maxHp;particles=[];if(fresh){round=1;playerWins=enemyWins=0;enemy.maxHp=108;enemy.hp=108}}
function showBanner(a,b=''){banner.innerHTML=`<small>${a}</small>${b}`;banner.classList.add('show');setTimeout(()=>banner.classList.remove('show'),1050)}
function attack(a,type='quick'){if(a.cool||a.defeated||a.block||a.dodge||(type==='special'&&a.energy<100))return;let s={quick:[.23,.34],heavy:[.4,.72],special:[.62,1.02]}[type];a.attack=s[0];a.cool=s[1];a.attackType=type;a.hit=false;if(type==='special')a.energy=0;beep(type==='special'?50:type==='heavy'?90:170,type==='special'?.18:.055,type==='quick'?'square':'sawtooth',type==='special'?.07:.035)}
function endRound(winner){winner===player?playerWins++:enemyWins++;let final=playerWins===2||enemyWins===2;showBanner(final?'FINAL VICTORY':`ROUND ${round} — ${winner===player?'SHADOW WINS':'RONIN WINS'}`,final?(winner===player?'THE SHADOW PREVAILS':'THE RONIN WINS'):'PREPARE FOR THE NEXT DUEL');if(final)setTimeout(()=>{running=false;start.classList.remove('hidden');start.querySelector('p:not(.eyebrow)').textContent=winner===player?'You conquered the midnight arena.':'The Ronin has claimed the arena. Try again?';startButton.innerHTML='FIGHT AGAIN <span>→</span>'},1800);else setTimeout(()=>{round++;reset(false);showBanner(`ROUND ${round}`,'FIGHT!')},1350)}
function hurt(t,s,d){if(t.flash||t.defeated||t.dodge)return;let guarded=t.block;if(guarded)d=Math.max(2,Math.ceil(d*.42));if(s===enemy)d=Math.ceil(d*(.98+(round-1)*.04));t.hp=Math.max(0,t.hp-d);t.flash=guarded?.1:.22;t.vx=(t.x-s.x>0?1:-1)*(guarded?75:d>15?390:220);t.vy=guarded?0:d>15?-270:-100;screenShake=guarded?.04:d>20?.25:.1;s.energy=Math.min(100,s.energy+d*1.5);s.combo=guarded?0:s.comboTimer>0?s.combo+1:1;s.comboTimer=.9;particles.push({x:t.x,y:t.y-74,n:guarded?5:d>15?18:8,color:guarded?'#98d9ff':s.color});beep(guarded?260:d>15?55:85,.12,guarded?'triangle':'sawtooth',.05);if(!t.hp){t.defeated=true;endRound(s)}}
function update(f,dt){f.cool=Math.max(0,f.cool-dt);f.attack=Math.max(0,f.attack-dt);f.flash=Math.max(0,f.flash-dt);f.block=Math.max(0,f.block-dt);f.dodge=Math.max(0,f.dodge-dt);f.comboTimer-=dt;if(f.comboTimer<0)f.combo=0;f.vy+=1150*dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.82;if(f.y>floor){f.y=floor;f.vy=0}f.x=Math.max(40,Math.min(W-40,f.x))}
function hitCheck(a,b){if(a.attack>0&&!a.hit&&a.attack<.18){let sp=a.attackType==='special',hv=a.attackType==='heavy',range=sp?180:hv?126:91;if(Math.abs(a.x-b.x)<range&&Math.abs(a.y-b.y)<110){a.hit=true;hurt(b,a,sp?31:hv?20:9)}}}
function input(){if(player.defeated)return;let l=keys.ArrowLeft||keys.KeyA,r=keys.ArrowRight||keys.KeyD;if(!player.attack){if(l)player.vx=-275;if(r)player.vx=275}if(l||r)player.flip=l;if((keys.Space||keys.KeyW)&&player.y>=floor){player.vy=-510;beep(250,.07,'triangle');keys.Space=keys.KeyW=false}if(keys.KeyJ){attack(player);keys.KeyJ=false}if(keys.KeyK){attack(player,'heavy');keys.KeyK=false}if(keys.KeyL){attack(player,'special');keys.KeyL=false}}
function ai(dt){if(enemy.defeated)return;let d=player.x-enemy.x,ad=Math.abs(d),dir=Math.sign(d);enemy.flip=d<0;if(player.attack&&ad<145&&!enemy.attack&&!enemy.dodge&&Math.random()<dt*(3.1+round*.7)){if((player.attackType==='heavy'||player.attackType==='special')&&Math.random()<.58){enemy.dodge=.16;enemy.vx=-dir*(460+round*20)}else if(player.attackType==='quick')enemy.block=.16}if(ad>135&&!enemy.attack&&!enemy.block)enemy.vx=dir*(180+round*16);else if(ad<80&&!enemy.attack&&!enemy.block)enemy.vx=-dir*(105+round*10);if(ad<128&&!enemy.cool&&!enemy.block&&!enemy.dodge&&Math.random()<dt*(2.15+round*.35)){let type=enemy.energy>=100&&Math.random()>.72?'special':Math.random()>.58?'heavy':'quick';attack(enemy,type);enemy.chain=type==='quick'&&Math.random()<.22?1:0}if(enemy.chain&&enemy.cool<.06&&ad<130){enemy.chain=0;attack(enemy,'quick')}}
function bg(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#101425');g.addColorStop(.7,'#33283d');g.addColorStop(1,'#101017');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ece2bc';ctx.globalAlpha=.9;ctx.beginPath();ctx.arc(825,150,78,0,7);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#28293a';for(let i=0;i<11;i++){let x=i*130-25,h=70+(i%4)*34;ctx.fillRect(x,390-h,90,h);ctx.fillRect(x+22,360-h,7,55)}ctx.fillStyle='#17151c';ctx.fillRect(0,floor+5,W,H-floor);ctx.strokeStyle='#bd9253';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,floor+5);ctx.lineTo(W,floor+5);ctx.stroke()}
function drawF(f){let d=f.flip?-1:1;ctx.save();ctx.translate(f.x,f.y);ctx.scale(d,1);if(f.flash)ctx.globalAlpha=.55;if(f.block){ctx.strokeStyle='#8fd7ff';ctx.globalAlpha=.7;ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,-72,62,-1.1,1.1);ctx.stroke();ctx.globalAlpha=1}if(f.dodge){ctx.globalAlpha=.45}ctx.fillStyle='#08090f';ctx.beginPath();ctx.moveTo(-25,-5);ctx.lineTo(28,-5);ctx.lineTo(37,-95);ctx.lineTo(13,-126);ctx.lineTo(-18,-119);ctx.lineTo(-35,-65);ctx.closePath();ctx.fill();ctx.fillStyle=f.color;ctx.fillRect(-15,-106,37,17);ctx.fillStyle='#d9c49e';ctx.fillRect(5,-101,17,16);ctx.fillStyle='#08090d';ctx.fillRect(15,-98,7,3);ctx.strokeStyle='#08090d';ctx.lineWidth=16;ctx.lineCap='round';let power=f.attackType==='special'?70:f.attackType==='heavy'?52:20;ctx.beginPath();ctx.moveTo(-7,-8);ctx.lineTo(-14+power,-48);ctx.moveTo(15,-8);ctx.lineTo(26,-55);ctx.stroke();ctx.strokeStyle=f.color;ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(-12,-76);ctx.lineTo(f.attack?power:30,-65);ctx.stroke();ctx.strokeStyle=f.attackType==='special'?'#b985ff':'#d5dbe0';ctx.lineWidth=f.attackType==='special'?7:3;ctx.beginPath();ctx.moveTo(23,-73);ctx.lineTo(f.attack?power+42:53,-84);ctx.stroke();if(f.attack){ctx.strokeStyle=f.attackType==='special'?'#a876ff':'#f4ca78';ctx.globalAlpha=.75;ctx.lineWidth=f.attackType==='special'?8:4;ctx.beginPath();ctx.arc(50,-80,f.attackType==='special'?62:35,-.7,.7);ctx.stroke()}ctx.restore()}
function meter(f,left){let x=left?45:W-405;ctx.fillStyle='#090a10';ctx.fillRect(x,36,360,19);ctx.fillStyle=f.color;ctx.fillRect(x+3,39,354*f.hp/f.maxHp,13);ctx.strokeStyle='#d2bd87';ctx.strokeRect(x,36,360,19);ctx.fillStyle='#eee5d4';ctx.font='700 18px Barlow Condensed';ctx.textAlign=left?'left':'right';ctx.fillText(f===enemy?'RONIN • BOSS':f.name,left?x:x+360,28);ctx.fillStyle='#0a0b12';ctx.fillRect(x,60,360,7);ctx.fillStyle=f.energy>=100?'#a978ff':'#66c6e8';ctx.fillRect(x,60,360*f.energy/100,7)}
function hud(){meter(player,true);meter(enemy,false);ctx.fillStyle='#c9aa68';ctx.font='700 17px Rajdhani';ctx.textAlign='center';ctx.fillText(`ROUND ${round}   •   ${playerWins} — ${enemyWins}`,W/2,39);if(player.combo>1){ctx.fillStyle='#f7d77d';ctx.font='800 25px Barlow Condensed';ctx.fillText(`${player.combo} HIT COMBO`,W/2,95)}if(player.energy>=100){ctx.fillStyle='#bd8cff';ctx.font='700 16px Rajdhani';ctx.fillText('SHADOW ART READY — PRESS L',W/2,120)}}
function loop(t){let dt=Math.min((t-last)/1000,.035);last=t;if(running){input();ai(dt);update(player,dt);update(enemy,dt);hitCheck(player,enemy);hitCheck(enemy,player);screenShake=Math.max(0,screenShake-dt);for(let p of particles)p.n-=dt*16;particles=particles.filter(p=>p.n>0)}ctx.save();let s=screenShake*18;ctx.translate((Math.random()-.5)*s,(Math.random()-.5)*s);bg();drawF(player);drawF(enemy);ctx.restore();hud();for(let p of particles){ctx.fillStyle=p.color;for(let i=0;i<4;i++)ctx.fillRect(p.x+(Math.random()-.5)*42,p.y+(Math.random()-.5)*45,4,4)}requestAnimationFrame(loop)}
function begin(){if(audio&&audio.state==='suspended')audio.resume();reset();running=true;start.classList.add('hidden');showBanner('ROUND 01','FIGHT!');beep(440,.1,'square',.04)}
startButton.addEventListener('click',begin);document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Space','KeyJ','KeyK','KeyL','KeyA','KeyD','KeyW'].includes(e.code))e.preventDefault();keys[e.code]=true});document.addEventListener('keyup',e=>keys[e.code]=false);document.querySelectorAll('[data-key]').forEach(b=>{let k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);keys[k]=true;if(k.startsWith('Key'))setTimeout(()=>keys[k]=false,70)});['pointerup','pointercancel','pointerleave'].forEach(x=>b.addEventListener(x,()=>keys[k]=false))});document.querySelector('#soundButton').addEventListener('click',e=>{sound=!sound;e.target.textContent=`♫ SOUND: ${sound?'ON':'OFF'}`});reset();requestAnimationFrame(loop);
